# Generated by Django 3.1.7 on 2021-04-09 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='number',
            new_name='Percentage',
        ),
    ]
